project_id = "tvbetqvpiypncjtkchcc"

[functions.create-payment]
verify_jwt = false

[functions.gmail-oauth]
verify_jwt = false

[functions.fetch-gmail-emails]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.ai-productivity-plan]
verify_jwt = true

[functions.secure-email-storage]
verify_jwt = true

[functions.enhanced-auth-security]
verify_jwt = false