version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"  # Frontend
      - "8082:8082"  # OAuth server
    environment:
      - NODE_ENV=production
      - PORT=8082
    env_file:
      - .env.production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/", "http://localhost:8082/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app_data: