// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvbetqvpiypncjtkchcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2YmV0cXZwaXlwbmNqdGtjaGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTUwNDEsImV4cCI6MjA2NzczMTA0MX0.48czLlDBqsom0Gj-Nhn9l0odqCnn48PZNcSc8_T7Yno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});